name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build sample java and deploy to minikube
    steps:
    - name: Build and push CONTAINER_NAME
      uses: ianbelcher/eks-kubectl-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        cluster_name: ${{ secrets.CLUSTER_NAME }}
        eks_role_arn: ${{ secrets.EKS_ROLE_ARN }}
    - name: Build image
      run: |
        export SHELL=/bin/bash
        docker build -f ./Dockerfile -t amirelgammal/sample-java .
        echo -n "verifying images:"
        docker images        
    - name: Deploy postgres
      run: |
        kubectl create ns sonar
        helm upgrade --install postgresql postgresql -f postgresql/values.yaml -n sonar
    - name: Deploy to sample app
      run: |
        helm upgrade --install sample-sonar deploy -n sonar
    - name: Test service URLs
      run: |
        minikube service list
        minikube service example --url
        echo "------------------opening the service------------------"
        # curl $(minikube service example --url)      
