name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build sample java and deploy to minikube
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ AWS_REGION }}
    - name: Build image
      run: |
        export SHELL=/bin/bash
        docker build -f ./Dockerfile -t amirelgammal/sample-java .
        echo -n "verifying images:"
        docker images        
    - name: Deploy postgres
      run: |
        kubectl create ns sonar
        helm upgrade --install postgresql postgresql -f postgresql/values.yaml -n sonar
    - name: Deploy to sample app
      run: |
        helm upgrade --install sample-sonar deploy -n sonar
    - name: Test service URLs
      run: |
        minikube service list
        minikube service example --url
        echo "------------------opening the service------------------"
        # curl $(minikube service example --url)      
